/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActivityList: typeof import('./../components/dashboard/ActivityList.vue')['default']
    AppProvider: typeof import('./../components/common/app-provider.vue')['default']
    AutoFillProgress: typeof import('./../components/dashboard/AutoFillProgress.vue')['default']
    EmbyScanProgress: typeof import('./../components/emby/EmbyScanProgress.vue')['default']
    EmbySeriesItem: typeof import('./../components/emby/EmbySeriesItem.vue')['default']
    EmbyStatsCards: typeof import('./../components/emby/EmbyStatsCards.vue')['default']
    HistoryTable: typeof import('./../components/auto-subscribe/HistoryTable.vue')['default']
    MediaCard: typeof import('./../components/MediaCard.vue')['default']
    NAlert: typeof import('naive-ui')['NAlert']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCollapse: typeof import('naive-ui')['NCollapse']
    NCollapseItem: typeof import('naive-ui')['NCollapseItem']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NPagination: typeof import('naive-ui')['NPagination']
    NProgress: typeof import('naive-ui')['NProgress']
    NRadioButton: typeof import('naive-ui')['NRadioButton']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpin: typeof import('naive-ui')['NSpin']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTag: typeof import('naive-ui')['NTag']
    NVirtualList: typeof import('naive-ui')['NVirtualList']
    PlatformPanel: typeof import('./../components/dashboard/PlatformPanel.vue')['default']
    PlatformStatus: typeof import('./../components/PlatformStatus.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScanProgress: typeof import('./../components/dashboard/ScanProgress.vue')['default']
    SourceConfigPanel: typeof import('./../components/auto-subscribe/SourceConfigPanel.vue')['default']
    StatsCards: typeof import('./../components/dashboard/StatsCards.vue')['default']
    StatusBadge: typeof import('./../components/StatusBadge.vue')['default']
    SubDialog: typeof import('./../components/SubDialog.vue')['default']
  }
}
